// Assembles the self-contained Framer files in framer/ from kit/:
// each kit/components/<Name>.tsx keeps its imports at the top and marks where
// shared code goes with `// @include helpers` / `// @include sphere`.
//
// Two outputs:
//  - framer/<Name>.tsx     one file per component, paste any one on its own
//  - framer/OffBrandKit.tsx every component in one file (named exports), one paste
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises"
import { resolve } from "node:path"

const root = resolve(import.meta.dirname, "..")
const shared = {
  helpers: await readFile(resolve(root, "kit/shared/helpers.tsx"), "utf8"),
  sphere: await readFile(resolve(root, "kit/shared/sphere.tsx"), "utf8"),
}
const banner = (name) =>
  `// Generated from kit/components/${name}.tsx by scripts/assemble.mjs. Edit the kit source, not this file.\n`

// Paste order in Framer's assets panel follows export order; keep it page order.
const ORDER = [
  "OffBrandNav", "OffBrandHero", "FeaturedWork", "IntroBlock", "LogoGrid", "Services",
  "Statement", "Testimonials", "CTA", "Footer", "PageHeader", "ContactDetails", "IridescentSphere",
]

await mkdir(resolve(root, "framer"), { recursive: true })
const files = (await readdir(resolve(root, "kit/components"))).filter((f) => f.endsWith(".tsx"))
const sources = new Map()
for (const file of files) {
  const src = await readFile(resolve(root, "kit/components", file), "utf8")
  sources.set(file.replace(/\.tsx$/, ""), src)
  const out = src.replace(/^\/\/ @include (\w+)\s*$/gm, (_, key) => {
    if (!shared[key]) throw new Error(`${file}: unknown include "${key}"`)
    return shared[key]
  })
  await writeFile(resolve(root, "framer", file), banner(file.replace(/\.tsx$/, "")) + out)
}

// Combined file: union of imports, shared code once, every component as a named export.
const importSpecs = new Map()
const bodies = []
for (const name of ORDER) {
  const src = sources.get(name)
  if (!src) throw new Error(`missing component ${name}`)
  const lines = src.split("\n")
  const body = []
  for (const line of lines) {
    const m = line.match(/^import (?:\* as (\w+)|\{([^}]+)\}) from "([^"]+)"/)
    if (m) {
      const set = importSpecs.get(m[3]) ?? new Set()
      if (m[1]) set.add(`* as ${m[1]}`)
      else m[2].split(",").map((s) => s.trim()).filter(Boolean).forEach((s) => set.add(s))
      importSpecs.set(m[3], set)
      continue
    }
    if (/^\/\/ @include /.test(line)) continue
    body.push(line)
  }
  bodies.push(body.join("\n").trim().replace(/^export default function (\w+)/m, "export function $1"))
}
const importLines = [...importSpecs.entries()].map(([mod, set]) => {
  const names = [...set]
  const star = names.find((n) => n.startsWith("* as "))
  return star ? `import ${star} from "${mod}"` : `import { ${names.sort().join(", ")} } from "${mod}"`
})
const combined = [
  "// Generated by scripts/assemble.mjs: every OFF+BRAND component in one Framer code file.",
  "// Paste this whole file into one code file in Framer and all components appear in Assets → Code.",
  "// Edit kit/ sources, not this file.",
  "",
  ...importLines,
  shared.helpers,
  shared.sphere,
  "",
  ...bodies.map((b, i) => `// ═══════════════════════════════════════════════════════════════════════════\n// ${ORDER[i]}\n// ═══════════════════════════════════════════════════════════════════════════\n\n${b}\n`),
].join("\n")
await writeFile(resolve(root, "framer/OffBrandKit.tsx"), combined)
console.log(`assembled ${files.length} components into framer/ and framer/OffBrandKit.tsx (${combined.split("\n").length} lines)`)
